// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfclqtbudstlthtnhqpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mY2xxdGJ1ZHN0bHRodG5ocXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MTczMjIsImV4cCI6MjA3MTQ5MzMyMn0.fBqsaTJFP3UyelwXIaIvHqCJwPBPIs77z98luN2qRrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});